version: "3.8"

services:
  traefik:
    image: traefik:v2.11
    container_name: "traefik"
    restart: unless-stopped
    ports:
      - "127.0.0.1:80:80"
      - "127.0.0.1:443:443"

      # Or use your IP address if you want to expose it on the network as well
      # Please note that you will not be able to use ".localhost" as your top level domain in this case
      # Use a top level domain like ".test" and then also configure a DNS server to point the domain to your IP address
      # - "192.168.0.123:80:80"
      # - "192.168.0.123:443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - ./traefik.yml:/traefik.yml:ro
      - ./traefik-dynamic.yml:/traefik-dynamic.yml:ro
      - "./tls:/tls:ro"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.entrypoints=http,https"
      - "traefik.http.routers.traefik.rule=Host(`traefik.localhost`)"
      - "traefik.http.routers.traefik.tls=true"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.middlewares=traefik-dashboard-auth"

      # Authentication middleware
      # It's highly recommended to not use the default!
      - "traefik.http.middlewares.traefik-dashboard-auth.basicauth.users=traefik:$$2y$$05$$JXeup1bn5WvFjmLTbwLBdukQG5.WYucOhvdBns/HVbGt3wP8kEmNS"
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  default:
    name: traefik-reverse-proxy
    external: true
