api:
  insecure: false
  dashboard: true

log:
  level: DEBUG
  filePath: "debug.log"
  format: json

accessLog:
  filePath: "access.log"
  bufferingSize: 100

entryPoints:
  http:
    address: ":80"
  https:
    address: ":443"

tracing:
  jaeger:
    samplingParam: 1.0
    samplingServerURL: "http://jaeger:5778/sampling"
    samplingType: "const"
    localAgentHostPort: "jaeger:6831"

providers:
  file:
    filename: /traefik-dynamic.yml
    watch: true
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
