api:
  insecure: false
  dashboard: true

log:
  level: DEBUG
  filePath: "debug.log"
  format: json

accessLog:
  filePath: "access.log"
  bufferingSize: 100

entryPoints:
  http:
    address: ":80"
    transport:
      respondingTimeouts:
        readTimeout: 3h
        writeTimeout: 0
        idleTimeout: 180s
  https:
    address: ":443"
    transport:
      respondingTimeouts:
        readTimeout: 3h
        writeTimeout: 0
        idleTimeout: 180s

tracing:
  serviceName: "traefik"
  otlp:
    grpc:
      endpoint: "jaeger:4317"
      insecure: true

providers:
  file:
    filename: /traefik-dynamic.yml
    watch: true
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
